/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcApi;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;

/**
 *
 * @author abdullahi
 */
public class B2ContextSelect extends javax.swing.JFrame {

    /**
     * Creates new form LanguageSpecifics
     */
    public B2ContextSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JPanel jPanel3 = new JPanel();
        JPanel jPanel6 = new JPanel();
        JLabel jLabel5 = new JLabel();
        JPanel jPanel8 = new JPanel();
        JLabel jLabel8 = new JLabel();
        JPanel jPanel4 = new JPanel();
        JLabel jLabel3 = new JLabel();
        JPanel jPanel5 = new JPanel();
        JLabel jLabel4 = new JLabel();
        JPanel jPanel7 = new JPanel();
        JLabel jLabel7 = new JLabel();
        JPanel jPanel9 = new JPanel();
        JLabel jLabel9 = new JLabel();
        JPanel jPanel10 = new JPanel();
        JLabel jLabel10 = new JLabel();
        JPanel jPanel2 = new JPanel();
        JLabel jLabel6 = new JLabel();
        JPanel jPanel11 = new JPanel();
        JLabel jLabel11 = new JLabel();
        JPanel jPanel12 = new JPanel();
        JLabel jLabel12 = new JLabel();
        JPanel jPanel13 = new JPanel();
        JLabel jLabel13 = new JLabel();
        JPanel jPanel14 = new JPanel();
        JLabel jLabel14 = new JLabel();

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("LEVEL B1 Context");

        jLabel2.setBackground(new Color(174, 79, 249));
        jLabel2.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(174, 79, 249));
        jLabel2.setText("Going shopping and asking for prices");

        jPanel3.setBackground(new Color(252, 245, 70));

        jPanel6.setBackground(new Color(252, 245, 70));

        jLabel5.setBackground(new Color(174, 79, 249));
        jLabel5.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new Color(174, 79, 249));
        jLabel5.setText("Making travel arrangements");

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new Color(252, 245, 70));

        jLabel8.setBackground(new Color(174, 79, 249));
        jLabel8.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new Color(174, 79, 249));
        jLabel8.setText("Socialising ");

        GroupLayout jPanel8Layout = new GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        jPanel4.setBackground(new Color(252, 245, 70));

        jLabel3.setBackground(new Color(174, 79, 249));
        jLabel3.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new Color(174, 79, 249));
        jLabel3.setText("Socialising ");

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel5.setBackground(new Color(252, 245, 70));

        jLabel4.setBackground(new Color(174, 79, 249));
        jLabel4.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new Color(174, 79, 249));
        jLabel4.setText("Work Life");

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jPanel7.setBackground(new Color(252, 245, 70));

        jLabel7.setBackground(new Color(174, 79, 249));
        jLabel7.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new Color(174, 79, 249));
        jLabel7.setText("Socialising ");

        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        jPanel9.setBackground(new Color(70, 230, 252));
        jPanel9.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel9.setForeground(new Color(255, 255, 255));
        jPanel9.setPreferredSize(new Dimension(65, 835));

        jLabel9.setBackground(new Color(174, 79, 249));
        jLabel9.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new Color(174, 79, 249));
        jLabel9.setText("Level B2");

        jPanel10.setBackground(new Color(70, 230, 252));
        jPanel10.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel10.setForeground(new Color(255, 255, 255));
        jPanel10.setPreferredSize(new Dimension(65, 835));

        jLabel10.setBackground(new Color(174, 79, 249));
        jLabel10.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new Color(174, 79, 249));
        jLabel10.setText("Level B2");

        GroupLayout jPanel10Layout = new GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel9))
            .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(174, 104, 194));

        jLabel6.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("Level B2 Context");

        jPanel11.setBackground(new Color(70, 230, 252));
        jPanel11.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel11.setForeground(new Color(255, 255, 255));
        jPanel11.setPreferredSize(new Dimension(65, 835));

        jLabel11.setBackground(new Color(174, 79, 249));
        jLabel11.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new Color(255, 255, 255));
        jLabel11.setText("Making travel arrangements");

        GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        jPanel12.setBackground(new Color(70, 230, 252));
        jPanel12.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel12.setForeground(new Color(255, 255, 255));
        jPanel12.setPreferredSize(new Dimension(65, 835));

        jLabel12.setBackground(new Color(174, 79, 249));
        jLabel12.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new Color(255, 255, 255));
        jLabel12.setText("Socialising in the country");

        GroupLayout jPanel12Layout = new GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        jPanel13.setBackground(new Color(70, 230, 252));
        jPanel13.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel13.setForeground(new Color(255, 255, 255));
        jPanel13.setPreferredSize(new Dimension(65, 835));

        jLabel13.setBackground(new Color(174, 79, 249));
        jLabel13.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setText("Going Shopping and asking for prices");

        GroupLayout jPanel13Layout = new GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        jPanel14.setBackground(new Color(70, 230, 252));
        jPanel14.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
        jPanel14.setForeground(new Color(255, 255, 255));
        jPanel14.setPreferredSize(new Dimension(65, 835));

        jLabel14.setBackground(new Color(174, 79, 249));
        jLabel14.setFont(new Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new Color(255, 255, 255));
        jLabel14.setText("Work life");

        GroupLayout jPanel14Layout = new GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addComponent(jLabel14))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, 296, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 281, GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel13, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B2ContextSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B2ContextSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B2ContextSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B2ContextSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B2ContextSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
